import { Bookmark, Topic, DashboardStats } from './types';

export const mockBookmarks: Bookmark[] = [
  {
    id: '1',
    url: 'https://x.com/naval/status/1829384710293',
    platform: 'x',
    title: 'Thread on wealth creation and leverage',
    author: '@naval',
    topic: 'Entrepreneurship',
    topicColor: '#F59E0B',
    status: 'pending',
    saved_at: '2026-04-12T10:30:00Z',
  },
  {
    id: '2',
    url: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
    platform: 'youtube',
    title: 'Full Body Workout — No Equipment (45 min)',
    author: 'Jeff Nippard',
    topic: 'Fitness',
    topicColor: '#EF4444',
    status: 'pending',
    saved_at: '2026-04-10T14:00:00Z',
  },
  {
    id: '3',
    url: 'https://x.com/karpathy/status/1829471029384',
    platform: 'x',
    title: 'Why transformers are eating the world — long thread',
    author: '@karpathy',
    topic: 'AI',
    topicColor: '#8B5CF6',
    status: 'reviewed',
    saved_at: '2026-04-09T08:15:00Z',
  },
  {
    id: '4',
    url: 'https://youtube.com/watch?v=abc123xyz',
    platform: 'youtube',
    title: 'How to Build a Second Brain (complete guide)',
    author: 'Ali Abdaal',
    topic: 'Productivity',
    topicColor: '#3B82F6',
    status: 'reviewed',
    saved_at: '2026-04-08T16:45:00Z',
  },
  {
    id: '5',
    url: 'https://x.com/paulg/status/19283746501928',
    platform: 'x',
    title: 'The real reason most startups fail',
    author: '@paulg',
    topic: 'Entrepreneurship',
    topicColor: '#F59E0B',
    status: 'pending',
    saved_at: '2026-04-11T12:00:00Z',
  },
  {
    id: '6',
    url: 'https://youtube.com/watch?v=cooking101',
    platform: 'youtube',
    title: 'Perfect Sourdough Bread — Beginner Friendly',
    author: 'Joshua Weissman',
    topic: 'Cooking',
    topicColor: '#F97316',
    status: 'snoozed',
    saved_at: '2026-04-07T09:30:00Z',
  },
  {
    id: '7',
    url: 'https://x.com/dan_abramov/status/8273649102',
    platform: 'x',
    title: 'React Server Components explained simply',
    author: '@dan_abramov',
    topic: 'Programming',
    topicColor: '#06B6D4',
    status: 'pending',
    saved_at: '2026-04-13T11:20:00Z',
  },
  {
    id: '8',
    url: 'https://youtube.com/watch?v=finance101',
    platform: 'youtube',
    title: 'Index Funds vs ETFs — What Nobody Tells You',
    author: 'Graham Stephan',
    topic: 'Finance',
    topicColor: '#10B981',
    status: 'reviewed',
    saved_at: '2026-04-06T20:00:00Z',
  },
  {
    id: '9',
    url: 'https://x.com/elonmusk/status/7362519283',
    platform: 'x',
    title: 'Thoughts on multiplanetary civilization',
    author: '@elonmusk',
    topic: 'Science',
    topicColor: '#6366F1',
    status: 'pending',
    saved_at: '2026-04-14T07:00:00Z',
  },
  {
    id: '10',
    url: 'https://youtube.com/watch?v=design01',
    platform: 'youtube',
    title: 'UI Design Fundamentals Every Developer Should Know',
    author: 'Juxtopposed',
    topic: 'Design',
    topicColor: '#EC4899',
    status: 'snoozed',
    saved_at: '2026-04-05T13:30:00Z',
  },
  {
    id: '11',
    url: 'https://x.com/sama/status/19287364501',
    platform: 'x',
    title: 'AGI timeline predictions and what it means for builders',
    author: '@sama',
    topic: 'AI',
    topicColor: '#8B5CF6',
    status: 'pending',
    saved_at: '2026-04-14T15:45:00Z',
  },
  {
    id: '12',
    url: 'https://youtube.com/watch?v=sleep101',
    platform: 'youtube',
    title: 'The Science of Sleep — Why 8 Hours Is Not Enough',
    author: 'Andrew Huberman',
    topic: 'Health',
    topicColor: '#14B8A6',
    status: 'pending',
    saved_at: '2026-04-13T22:10:00Z',
  },
  {
    id: '13',
    url: 'https://x.com/jasonfried/status/827364910',
    platform: 'x',
    title: 'Remote work is not a trend, it is the future of work',
    author: '@jasonfried',
    topic: 'Productivity',
    topicColor: '#3B82F6',
    status: 'reviewed',
    saved_at: '2026-04-04T10:00:00Z',
  },
];

export const mockTopics: Topic[] = [
  { id: '1', name: 'AI', color: '#8B5CF6', count: 2 },
  { id: '2', name: 'Entrepreneurship', color: '#F59E0B', count: 2 },
  { id: '3', name: 'Fitness', color: '#EF4444', count: 1 },
  { id: '4', name: 'Productivity', color: '#3B82F6', count: 2 },
  { id: '5', name: 'Programming', color: '#06B6D4', count: 1 },
  { id: '6', name: 'Finance', color: '#10B981', count: 1 },
  { id: '7', name: 'Design', color: '#EC4899', count: 1 },
  { id: '8', name: 'Health', color: '#14B8A6', count: 1 },
  { id: '9', name: 'Cooking', color: '#F97316', count: 1 },
  { id: '10', name: 'Science', color: '#6366F1', count: 1 },
];

export const mockStats: DashboardStats = {
  saved_this_week: 12,
  saved_last_week: 8,
  pending_review: 28,
  top_topic: 'AI',
  review_streak_weeks: 3,
  platform_breakdown: { x: 7, youtube: 6 },
};
